apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-slaves
  labels:
    jmeter_mode: slave
spec:
  replicas: 3
  selector:
    matchLabels:
      jmeter_mode: slave
  template:
    metadata:
      labels:
        jmeter_mode: slave
    spec:
      containers:
        - name: jmslave
          image: 411396279728.dkr.ecr.ap-northeast-1.amazonaws.com/jmeter-slave:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1099
            - containerPort: 50000
          env:
            - name: HEAP
              value: "-Xms1G -Xmx2G"
          resources: {}
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: node
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              jmeter_mode: slave
