apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-slaves
  labels:
    jmeter_mode: slave
spec:
  replicas: 8
  selector:
    matchLabels:
      jmeter_mode: slave
  template:
    metadata:
      labels:
        jmeter_mode: slave
    spec:
      containers:
        - name: jmslave
          image: 411396279728.dkr.ecr.ap-northeast-1.amazonaws.com/jmeter-slave:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1099
            - containerPort: 50000
          resources: {}
          #  requests:
          #    memory: "1500Mi"
          #    cpu: "200m"
          #  limits:
          #    memory: "1500Mi"
          #    cpu: "200m"
      
      #topologySpreadConstraints:
      #  - maxSkew: 1
      #    topologyKey: node
      #    whenUnsatisfiable: DoNotSchedule #ScheduleAnyway
      #    labelSelector:
      #      matchLabels:
      #        jmeter_mode: slave   