apiVersion: apps/v1
kind: Deployment
metadata:
  name: jmeter-master
  namespace: jmeter
  labels:
    jmeter_mode: master
spec:
  replicas: 1
  selector:
    matchLabels:
      jmeter_mode: master
  template:
    metadata:
      labels:
        jmeter_mode: master
        app: jmeter-master
      name: jmeter-master #ポッド名
    spec:
      serviceAccountName: datadog-agent
      shareProcessNamespace: true
      containers:
        - image: 411396279728.dkr.ecr.ap-northeast-1.amazonaws.com/jmeter-master:latest
          name: jmeter-master
          imagePullPolicy: IfNotPresent
          command: ["/bin/bash", "-c", "--"]
          args: ["while true; do sleep 30; done;"]
          volumeMounts:
            - name: loadtest
              mountPath: /load_test
              subPath: "load_test"
          ports:
            - containerPort: 60000
        - image: datadog/agent:latest
          name: datadog-agent
          ports:
            - containerPort: 8125
              name: dogstatsdport
              protocol: UDP
          env:
            - name: DD_API_KEY
              value: "a9626e677fd0def1ef4945944e91cf36"
              valueFrom:
                configMapKeyRef:
                  name: datadog-cm
                  key:  DD_API_KEY
            - name: DD_SITE
              value: "datadoghq.com"
            - name: DD_EKS_FARGATE
              value: "true"
            - name: DD_KUBERNETES_KUBELET_NODENAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: spec.nodeName
          resources:
              requests:
                memory: "256Mi"
                cpu: "200m"
              limits:
                memory: "256Mi"
                cpu: "200m"
      volumes:
        - name: loadtest
          configMap:
            name: jmeter-load-test
