apiVersion: v1
kind: Service
metadata:
  name: apache-bench
  namespace: jmeter
  labels:
    app: apache-bench
spec:
  ports:
    - name: http 
      port: 80
  selector:
    app: apache-bench
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-bench
  namespace: jmeter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-bench
  template:
    metadata:
      name: apache-bench
      namespace: jmeter
      labels: 
        app: apache-bench
    spec:
      containers:
        - name: apache-bench
          image: mocoso/apachebench
          ports:
            - containerPort: 80   
          command: [ "/bin/bash", "-c", "--" ]
          args: [ "while true; do sleep 30; done;" ]
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                app: echoserver #differnt nodes
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                deployment: wso2am-pattern-3-am-gateway #prefer different nodes   

