apiVersion: v1
kind: Service
metadata:
  name: echoserver
  namespace: jmeter
  labels:
    app: echoserver
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
  selector:
    app: echoserver
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
  namespace: jmeter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      name: echoserver
      namespace: jmeter
      labels:
        app: echoserver
    spec:
      containers:
      - image: k8s.gcr.io/echoserver:1.4
        imagePullPolicy: IfNotPresent
        name: echoserver
        ports:
        - containerPort: 80
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: node
          whenUnsatisfiable: DoNotSchedule #ScheduleAnyway
          labelSelector:
            matchLabels:
              app: echoserver
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - topologyKey: kubernetes.io/hostname
            labelSelector:
              matchLabels:
                jmeter_mode: slave